CC = clang++

ARGS = -std=c++20 -pedantic-errors -Wall -Weffc++ -Wextra -Wconversion -Wsign-conversion -g

TARGET = ll

SRCS = ll.cpp


all: $(TARGET)

$(TARGET): $(SRCS)
	$(CC) $(ARGS) -o $(TARGET) $(SRCS)

